# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: OpenTabletDriver
description: >- # this means to ignore newlines until "baseurl:"
  OpenTabletDriver is an open source, cross-platform, low latency, user-mode tablet driver.
baseurl: "" # webserver path, blank for GitHub pages
url: https://opentabletdriver.net # full URI to website

sass:
  sass_dir: _sass

# Site variables
latest_otd_version: v0.6.3.0

otd_release_url:
  https://github.com/OpenTabletDriver/OpenTabletDriver/releases/latest/download # no slash at end
discord_invite_url: https://discord.gg/9bcMaPkVAR
github_otd_repo_url: https://github.com/OpenTabletDriver/OpenTabletDriver

# Sets default values according to scope
# See https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: "" # apply to everything
    values:
      layout: "default"
  -
    scope:
      type: "wiki" # apply to collection: 'wiki' only (see collections array below)
    values:
      layout: "wikipage"

# Assign _folder settings, e.g. _sections, _wiki
# See: https://jekyllrb.com/docs/collections/#collections
collections:
  sections:
    output: true
    permalink: /:path
  wiki:
    output: true
    permalink: /Wiki/:path # this allows us to use infinitely deep subdirs

# excludes:
