name: Extract Jekyll site

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: "site/"
          ruby-version: '3.2' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build site
        run: |
          cd site
          bundle exec jekyll build

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "site/_site/"
