name: Jekyll CI

on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  build:
    uses: ./.github/workflows/jekyll-build-workflow.yml
  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/workflows/site-workflow

      - name: Run tests
        run: ./run-tests.sh || exit 1

  internal-links:
    name: "Absolute Internal Links"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/workflows/site-workflow

      - name: Check for internal absolute links
        run: bash -c "! grep -REi 'https?://(www.)?opentabletdriver.net' _site || exit 1"

  html-validation:
    name: "Validate HTML"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/workflows/site-workflow

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Load Cache HTMLProofer
        id: cache-htmlproofer
        uses: actions/cache/restore@v3
        with:
          path: tmp/.htmlproofer
          key: ${{ runner.os }}-htmlproofer

      - name: Check final HTML with html-proofer
        run: |
          gem install html-proofer
          rake htmlproofer

      - name: Save Cache HTMLProofer
        uses: actions/cache/save@v3
        if: always()
        with:
          path: tmp/.htmlproofer
          key: ${{ runner.os }}-htmlproofer
