name: Linting

on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Linting with editorconfig-checker
        run: |
          docker run --rm --volume=${{ github.workspace }}:/check mstruebing/editorconfig-checker
