name: Extract Jekyll site

on:
  workflow_call:

jobs:
  build:
    steps:
    - uses: ./.github/workflows/jekyll-build-workflow.yml
  extract:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get site artifact
        uses: actions/download-artifact@v3
        with:
          name: github-pages

      - name: Extract site
        run: |
          mkdir _site || exit 1
          tar -C _site -xf artifact.tar || exit 1
          rm artifact.tar
